# Generated by Django 4.2.17 on 2025-03-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0005_manager_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdetails',
            name='employee_cancel_status',
            field=models.BooleanField(default=False),
        ),
    ]
